name: pokemon_sample_app
description: Sample flutter app using pokeapi.co

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^6.1.1
  get_it: ^5.0.3
  injectable: ^1.0.7
  cached_network_image: ^2.2.0+1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^0.12.0
  retrofit: ^1.3.4+1
  dio: ^3.0.10
  json_annotation: ^3.1.0
  dartz: ^0.9.2

dev_dependencies:
  build_runner: ^1.8.0
  freezed: ^0.12.7
  json_serializable: ^3.2.5
  injectable_generator: ^1.0.7
  flutter_test:
    sdk: flutter
  retrofit_generator: ^1.4.1

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true